# Generated by Django 2.0.2 on 2018-05-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reptiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='public/uploads/lizard/')),
            ],
        ),
        migrations.CreateModel(
            name='Lizard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=256, verbose_name='Nom scientifique')),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('sex', models.CharField(help_text='format: x.y.z', max_length=11)),
                ('moeurs', models.CharField(choices=[('S', 'Semi-fouisseur'), ('F', 'Fouisseur'), ('T', 'Terrestre'), ('R', 'Semi-arboricole'), ('A', 'Arboricole')], default='A', max_length=1, verbose_name='Moeurs')),
                ('reproduction', models.CharField(choices=[('O', 'Ovipare'), ('V', 'Vivipare'), ('I', 'Ovovipare'), ('P', 'Parthénogenèse')], default='O', max_length=1, verbose_name='Reproduction')),
                ('life', models.CharField(choices=[('C', 'Crépusculaire'), ('D', 'Diurne'), ('N', 'Nocturne')], default='N', max_length=1, verbose_name='Mode de vie')),
                ('environment', models.ManyToManyField(to='reptiles.Environment')),
                ('repartition', models.ManyToManyField(to='reptiles.Repartition')),
            ],
            options={
                'verbose_name': 'Lézard',
                'verbose_name_plural': 'Lézards',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='lizard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lizardsalbum', related_query_name='lizardalbum', to='lizard.Lizard'),
        ),
    ]
