# Generated by Django 2.0.2 on 2018-02-20 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reptiles', '0007_auto_20180220_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lizard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=256, verbose_name='Nom scientifique')),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('sex', models.CharField(max_length=11)),
                ('price', models.FloatField(blank=True, null=True, verbose_name='prix')),
                ('price_couple', models.FloatField(blank=True, null=True, verbose_name='prix de couple')),
                ('business', models.CharField(blank=True, choices=[('-', ' '), ('A', 'À vendre'), ('R', 'Recherche')], default='-', max_length=1, null=True, verbose_name='Achat ou vente')),
                ('environment', models.ManyToManyField(to='reptiles.Environment')),
                ('life', models.ManyToManyField(to='reptiles.Life')),
                ('repartition', models.ManyToManyField(to='reptiles.Repartition')),
                ('reproduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptiles.Reproduction')),
            ],
            options={
                'verbose_name': 'Lézard',
                'verbose_name_plural': 'Lézards',
            },
        ),
    ]
