# Generated by Django 2.0.2 on 2018-02-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lizard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lizard',
            name='business',
        ),
        migrations.RemoveField(
            model_name='lizard',
            name='price',
        ),
        migrations.RemoveField(
            model_name='lizard',
            name='price_couple',
        ),
    ]
