# Generated by Django 2.0.2 on 2018-02-22 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lizard', '0002_auto_20180222_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='public/uploads/lizard/')),
                ('lizard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lizardsalbum', related_query_name='lizardalbum', to='lizard.Lizard')),
            ],
        ),
    ]
