# Generated by Django 2.0.2 on 2018-02-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lizard', '0003_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='lizard',
            name='moeurs',
            field=models.CharField(choices=[('S', 'Semi-fouisseur'), ('F', 'Fouisseur'), ('T', 'Terrestre'), ('R', 'Semi-arboricole'), ('A', 'Arboricole')], default='A', max_length=1, verbose_name='Moeurs'),
        ),
        migrations.RemoveField(
            model_name='lizard',
            name='life',
        ),
        migrations.AddField(
            model_name='lizard',
            name='life',
            field=models.CharField(choices=[('C', 'Crépusculaire'), ('D', 'Diurne'), ('N', 'Nocturne')], default='N', max_length=1, verbose_name='Mode de vie'),
        ),
        migrations.AlterField(
            model_name='lizard',
            name='reproduction',
            field=models.CharField(choices=[('O', 'Ovipare'), ('V', 'Vivipare'), ('I', 'Ovovipare'), ('P', 'Parthénogenèse')], default='O', max_length=1, verbose_name='Reproduction'),
        ),
        migrations.AlterField(
            model_name='lizard',
            name='sex',
            field=models.CharField(help_text='format: x.y.z', max_length=11),
        ),
    ]
