# Generated by Django 2.0.2 on 2018-05-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reptiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='public/uploads/snakes/')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumForSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='public/uploads/snakes/for_sale/')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nom')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Famille',
                'verbose_name_plural': 'Familles',
            },
        ),
        migrations.CreateModel(
            name='SalingSnake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField()),
                ('disponibilities', models.CharField(help_text='format: x.y.z', max_length=11, verbose_name='Disponibilité(s)')),
                ('subject', models.NullBooleanField(verbose_name='Soumis à autorisation')),
                ('comments', models.TextField()),
                ('price', models.FloatField(verbose_name='Prix')),
                ('price_couple', models.FloatField(blank=True, null=True, verbose_name='Prix de couple')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snake.Family')),
            ],
            options={
                'verbose_name': 'Espèce à vendre',
                'verbose_name_plural': 'Espèces à vendre',
            },
        ),
        migrations.CreateModel(
            name='SearchingSnake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_list', models.TextField(verbose_name="Liste d'espèces")),
            ],
            options={
                'verbose_name': 'Espèces recherchées',
                'verbose_name_plural': 'Espèces recherchées',
            },
        ),
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=256, verbose_name='Nom scientifique')),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('sex', models.CharField(help_text='format: x.y.z', max_length=11)),
                ('moeurs', models.CharField(choices=[('S', 'Semi-fouisseur'), ('F', 'Fouisseur'), ('T', 'Terrestre'), ('R', 'Semi-arboricole'), ('A', 'Arboricole')], default='A', max_length=1, verbose_name='Moeurs')),
                ('reproduction', models.CharField(choices=[('O', 'Ovipare'), ('V', 'Vivipare'), ('I', 'Ovovipare'), ('P', 'Parthénogenèse')], default='O', max_length=1, verbose_name='Reproduction')),
                ('life', models.CharField(choices=[('C', 'Crépusculaire'), ('D', 'Diurne'), ('N', 'Nocturne')], default='N', max_length=1, verbose_name='Mode de vie')),
                ('dentition', models.CharField(choices=[('A', 'Aglyphe'), ('O', 'Opistoglyphe'), ('P', 'Proteroglyphe'), ('I', 'Opistodonte'), ('S', 'Solenoglyphe')], default='A', max_length=1)),
                ('old', models.BooleanField(verbose_name='Ancien serpent')),
                ('newborn', models.BooleanField(verbose_name='Nouvelles naissances')),
                ('environment', models.ManyToManyField(to='reptiles.Environment')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snake.Family')),
                ('repartition', models.ManyToManyField(to='reptiles.Repartition')),
            ],
            options={
                'verbose_name': 'Serpent',
                'verbose_name_plural': 'Serpents',
            },
        ),
        migrations.CreateModel(
            name='Venom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Toxicologie',
                'verbose_name_plural': 'Toxixcologies',
            },
        ),
        migrations.AddField(
            model_name='snake',
            name='venom',
            field=models.ManyToManyField(blank=True, to='snake.Venom'),
        ),
        migrations.AddField(
            model_name='salingsnake',
            name='venom',
            field=models.ManyToManyField(blank=True, to='snake.Venom'),
        ),
        migrations.AddField(
            model_name='albumforsale',
            name='snake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snakesalbum', related_query_name='snakealbum', to='snake.SalingSnake'),
        ),
        migrations.AddField(
            model_name='album',
            name='snake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snakesalbum', related_query_name='snakealbum', to='snake.Snake'),
        ),
    ]
