# Generated by Django 2.0.2 on 2018-02-20 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reptiles', '0007_auto_20180220_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nom')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Famille',
                'verbose_name_plural': 'Familles',
            },
        ),
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=256, verbose_name='Nom scientifique')),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('sex', models.CharField(max_length=11)),
                ('price', models.FloatField(blank=True, null=True, verbose_name='prix')),
                ('price_couple', models.FloatField(blank=True, null=True, verbose_name='prix de couple')),
                ('business', models.CharField(blank=True, choices=[('-', ' '), ('A', 'À vendre'), ('R', 'Recherche')], default='-', max_length=1, null=True, verbose_name='Achat ou vente')),
                ('dentition', models.CharField(choices=[('A', 'Aglyphe'), ('O', 'Opistoglyphe'), ('P', 'Proteroglyphe'), ('I', 'Opistodonte'), ('S', 'Solenoglyphe')], default='A', max_length=1)),
                ('environment', models.ManyToManyField(to='reptiles.Environment')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snake.Family')),
                ('life', models.ManyToManyField(to='reptiles.Life')),
                ('repartition', models.ManyToManyField(to='reptiles.Repartition')),
                ('reproduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptiles.Reproduction')),
            ],
            options={
                'verbose_name': 'Serpent',
                'verbose_name_plural': 'Serpents',
            },
        ),
        migrations.CreateModel(
            name='Venom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Toxicologie',
                'verbose_name_plural': 'Toxixcologies',
            },
        ),
        migrations.AddField(
            model_name='snake',
            name='venom',
            field=models.ManyToManyField(blank=True, null=True, to='snake.Venom'),
        ),
    ]
