# Generated by Django 2.0.2 on 2018-02-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snake',
            name='old',
            field=models.NullBooleanField(verbose_name='Ancien serpent'),
        ),
    ]
