# Generated by Django 2.0.2 on 2018-05-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salingsnake',
            name='scientific_name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
    ]
