# Generated by Django 2.0.2 on 2018-02-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0002_snake_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snake',
            name='old',
            field=models.BooleanField(default=True, verbose_name='Ancien serpent'),
            preserve_default=False,
        ),
    ]
