# Generated by Django 2.0.2 on 2018-02-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0003_auto_20180222_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snake',
            name='business',
            field=models.CharField(blank=True, choices=[('A', 'À vendre'), ('R', 'Recherche')], default='-', max_length=1, null=True, verbose_name='Achat ou vente'),
        ),
    ]
