# Generated by Django 2.0.2 on 2018-02-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0004_auto_20180222_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='public/uploads/snakes/')),
            ],
        ),
        migrations.AlterField(
            model_name='snake',
            name='business',
            field=models.CharField(blank=True, choices=[('A', 'À vendre'), ('R', 'Recherche')], default=' ', max_length=1, null=True, verbose_name='Achat ou vente'),
        ),
        migrations.AddField(
            model_name='album',
            name='snake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snake.Snake'),
        ),
    ]
