# Generated by Django 2.0.2 on 2018-02-22 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0005_auto_20180222_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='snake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snakesalbum', related_query_name='snakealbum', to='snake.Snake'),
        ),
    ]
