# Generated by Django 2.0.2 on 2018-03-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0008_auto_20180224_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='snake',
            name='newborn',
            field=models.BooleanField(default=False, verbose_name='Nouvelles naissances'),
            preserve_default=False,
        ),
    ]
