# Generated by Django 2.0.2 on 2018-03-17 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0009_snake_newborn'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyForSearch',
            fields=[
                ('family_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snake.Family')),
            ],
            bases=('snake.family',),
        ),
        migrations.CreateModel(
            name='SearchSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=256, verbose_name='Nom scientifique')),
                ('price', models.FloatField(verbose_name='Prix')),
                ('price_couple', models.FloatField(verbose_name='Prix de couple')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', related_query_name='family', to='snake.Family')),
            ],
            options={
                'verbose_name': 'Espèce recherchée',
                'verbose_name_plural': 'Espèces recherchées',
            },
        ),
        migrations.RemoveField(
            model_name='snake',
            name='business',
        ),
        migrations.RemoveField(
            model_name='snake',
            name='price',
        ),
        migrations.RemoveField(
            model_name='snake',
            name='price_couple',
        ),
    ]
