# Generated by Django 2.0.2 on 2018-03-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0010_auto_20180317_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchspecies',
            old_name='family',
            new_name='FamilyForSearch',
        ),
    ]
