# Generated by Django 2.0.2 on 2018-03-17 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0012_auto_20180317_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchspecies',
            name='FamilyForSearch',
        ),
        migrations.AddField(
            model_name='searchspecies',
            name='family',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='families', related_query_name='family', to='snake.FamilyForSearch'),
            preserve_default=False,
        ),
    ]
