# Generated by Django 2.0.2 on 2018-04-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0011_auto_20180317_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchingSnake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_list', models.TextField(verbose_name="Liste d'espèces")),
            ],
        ),
    ]
