# Generated by Django 2.0.2 on 2018-04-16 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0012_auto_20180416_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchingsnake',
            options={'verbose_name': 'Espèches recherchées', 'verbose_name_plural': 'Espèches recherchées'},
        ),
    ]
