# Generated by Django 2.0.2 on 2018-03-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0012_auto_20180317_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyforsearch',
            name='family_ptr',
        ),
        migrations.RemoveField(
            model_name='searchspecies',
            name='family',
        ),
        migrations.DeleteModel(
            name='FamilyForSearch',
        ),
        migrations.DeleteModel(
            name='SearchSpecies',
        ),
    ]
