# Generated by Django 2.0.2 on 2018-04-16 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reptiles', '0008_auto_20180224_2155'),
        ('snake', '0013_auto_20180416_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumForSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='public/uploads/snakes/for_sale/')),
            ],
        ),
        migrations.CreateModel(
            name='SalingSnake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=256, verbose_name='Nom scientifique')),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('sex', models.CharField(help_text='format: x.y.z', max_length=11)),
                ('moeurs', models.CharField(choices=[('S', 'Semi-fouisseur'), ('F', 'Fouisseur'), ('T', 'Terrestre'), ('R', 'Semi-arboricole'), ('A', 'Arboricole')], default='A', max_length=1, verbose_name='Moeurs')),
                ('reproduction', models.CharField(choices=[('O', 'Ovipare'), ('V', 'Vivipare'), ('I', 'Ovovipare'), ('P', 'Parthénogenèse')], default='O', max_length=1, verbose_name='Reproduction')),
                ('life', models.CharField(choices=[('C', 'Crépusculaire'), ('D', 'Diurne'), ('N', 'Nocturne')], default='N', max_length=1, verbose_name='Mode de vie')),
                ('dentition', models.CharField(choices=[('A', 'Aglyphe'), ('O', 'Opistoglyphe'), ('P', 'Proteroglyphe'), ('I', 'Opistodonte'), ('S', 'Solenoglyphe')], default='A', max_length=1)),
                ('price', models.FloatField(verbose_name='Prix')),
                ('price_couple', models.FloatField(blank=True, verbose_name='Prix de couple')),
                ('environment', models.ManyToManyField(to='reptiles.Environment')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snake.Family')),
                ('repartition', models.ManyToManyField(to='reptiles.Repartition')),
                ('venom', models.ManyToManyField(blank=True, to='snake.Venom')),
            ],
            options={
                'verbose_name': 'Reptile',
                'verbose_name_plural': 'Reptiles',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='albumforsale',
            name='snake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snakesalbum', related_query_name='snakealbum', to='snake.SalingSnake'),
        ),
    ]
