# Generated by Django 2.0.2 on 2018-04-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0014_searchingsnake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchingSnake',
        ),
    ]
