# Generated by Django 2.0.2 on 2018-04-16 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0014_auto_20180416_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salingsnake',
            options={'verbose_name': 'Espèce à vendre', 'verbose_name_plural': 'Espèces à vendre'},
        ),
    ]
