# Generated by Django 2.0.2 on 2018-04-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0015_auto_20180416_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salingsnake',
            name='price_couple',
            field=models.FloatField(blank=True, null=True, verbose_name='Prix de couple'),
        ),
    ]
