# Generated by Django 2.0.2 on 2018-04-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0016_auto_20180416_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salingsnake',
            old_name='description',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='salingsnake',
            name='dentition',
        ),
        migrations.RemoveField(
            model_name='salingsnake',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='salingsnake',
            name='life',
        ),
        migrations.RemoveField(
            model_name='salingsnake',
            name='moeurs',
        ),
        migrations.RemoveField(
            model_name='salingsnake',
            name='repartition',
        ),
        migrations.RemoveField(
            model_name='salingsnake',
            name='reproduction',
        ),
        migrations.RemoveField(
            model_name='salingsnake',
            name='sex',
        ),
        migrations.AddField(
            model_name='salingsnake',
            name='disponibilities',
            field=models.CharField(default='1.1', help_text='format: x.y.z', max_length=11, verbose_name='Disponibilité(s)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salingsnake',
            name='subject',
            field=models.NullBooleanField(verbose_name='Soumis à autorisation'),
        ),
        migrations.AlterField(
            model_name='salingsnake',
            name='scientific_name',
            field=models.CharField(max_length=32, verbose_name='Nom'),
        ),
    ]
