# Generated by Django 2.0.2 on 2018-05-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Environnement',
                'verbose_name_plural': 'Environnements',
            },
        ),
        migrations.CreateModel(
            name='Repartition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Répartition',
                'verbose_name_plural': 'Répartitions',
            },
        ),
    ]
