# Generated by Django 2.0.2 on 2018-02-19 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nom')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Life',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Lizard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=256, verbose_name='Nom scientifique')),
                ('slug', models.SlugField()),
                ('sex', models.CharField(max_length=11)),
                ('price', models.FloatField(blank=True, null=True, verbose_name='prix')),
                ('price_couple', models.FloatField(blank=True, null=True, verbose_name='prix de couple')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptiles.Environment')),
                ('life', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptiles.Life')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=256, verbose_name='Nom scientifique')),
                ('slug', models.SlugField()),
                ('sex', models.CharField(max_length=11)),
                ('price', models.FloatField(blank=True, null=True, verbose_name='prix')),
                ('price_couple', models.FloatField(blank=True, null=True, verbose_name='prix de couple')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptiles.Environment')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptiles.Family')),
                ('life', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptiles.Life')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
