# Generated by Django 2.0.2 on 2018-02-20 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reptiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Reproduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Venom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nom')),
            ],
        ),
        migrations.AddField(
            model_name='lizard',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snake',
            name='dentition',
            field=models.CharField(choices=[('A', 'Aglyphe'), ('O', 'Opistoglyphe'), ('P', 'Proteroglyphe'), ('I', 'Opistodonte'), ('S', 'Solenoglyphe')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snake',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lizard',
            name='repartition',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reptiles.Repartition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lizard',
            name='reproduction',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reptiles.Reproduction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snake',
            name='repartition',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reptiles.Repartition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snake',
            name='reproduction',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reptiles.Reproduction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snake',
            name='venom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reptiles.Venom'),
            preserve_default=False,
        ),
    ]
