# Generated by Django 2.0.2 on 2018-02-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptiles', '0002_auto_20180220_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='snake',
            name='business',
            field=models.CharField(blank=True, choices=[('A', 'À vendre'), ('R', 'Recherche')], max_length=1, null=True, verbose_name='Achat ou vente'),
        ),
        migrations.RemoveField(
            model_name='lizard',
            name='environment',
        ),
        migrations.AddField(
            model_name='lizard',
            name='environment',
            field=models.ManyToManyField(to='reptiles.Environment'),
        ),
        migrations.RemoveField(
            model_name='lizard',
            name='life',
        ),
        migrations.AddField(
            model_name='lizard',
            name='life',
            field=models.ManyToManyField(to='reptiles.Life'),
        ),
        migrations.RemoveField(
            model_name='lizard',
            name='repartition',
        ),
        migrations.AddField(
            model_name='lizard',
            name='repartition',
            field=models.ManyToManyField(to='reptiles.Repartition'),
        ),
        migrations.RemoveField(
            model_name='snake',
            name='environment',
        ),
        migrations.AddField(
            model_name='snake',
            name='environment',
            field=models.ManyToManyField(to='reptiles.Environment'),
        ),
        migrations.RemoveField(
            model_name='snake',
            name='life',
        ),
        migrations.AddField(
            model_name='snake',
            name='life',
            field=models.ManyToManyField(to='reptiles.Life'),
        ),
        migrations.RemoveField(
            model_name='snake',
            name='repartition',
        ),
        migrations.AddField(
            model_name='snake',
            name='repartition',
            field=models.ManyToManyField(to='reptiles.Repartition'),
        ),
        migrations.RemoveField(
            model_name='snake',
            name='venom',
        ),
        migrations.AddField(
            model_name='snake',
            name='venom',
            field=models.ManyToManyField(blank=True, null=True, to='reptiles.Venom'),
        ),
    ]
