# Generated by Django 2.0.2 on 2018-02-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptiles', '0003_auto_20180220_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='lizard',
            name='business',
            field=models.CharField(blank=True, choices=[('-', ' '), ('A', 'À vendre'), ('R', 'Recherche')], default='-', max_length=1, null=True, verbose_name='Achat ou vente'),
        ),
        migrations.AlterField(
            model_name='snake',
            name='business',
            field=models.CharField(blank=True, choices=[('-', ' '), ('A', 'À vendre'), ('R', 'Recherche')], default='-', max_length=1, null=True, verbose_name='Achat ou vente'),
        ),
        migrations.AlterField(
            model_name='snake',
            name='dentition',
            field=models.CharField(choices=[('A', 'Aglyphe'), ('O', 'Opistoglyphe'), ('P', 'Proteroglyphe'), ('I', 'Opistodonte'), ('S', 'Solenoglyphe')], default='A', max_length=1),
        ),
    ]
