# Generated by Django 2.0.2 on 2018-02-20 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reptiles', '0004_auto_20180220_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environment',
            options={'verbose_name': 'Environnement', 'verbose_name_plural': 'Environnements'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Famille', 'verbose_name_plural': 'Familles'},
        ),
        migrations.AlterModelOptions(
            name='life',
            options={'verbose_name': 'Mode de vie', 'verbose_name_plural': 'Modes de vie'},
        ),
        migrations.AlterModelOptions(
            name='lizard',
            options={'verbose_name': 'Lézard', 'verbose_name_plural': 'Lézards'},
        ),
        migrations.AlterModelOptions(
            name='repartition',
            options={'verbose_name': 'Répartition', 'verbose_name_plural': 'Répartitions'},
        ),
        migrations.AlterModelOptions(
            name='reproduction',
            options={'verbose_name': 'Reproduction', 'verbose_name_plural': 'Reproductions'},
        ),
        migrations.AlterModelOptions(
            name='snake',
            options={'verbose_name': 'Serpent', 'verbose_name_plural': 'Serpents'},
        ),
        migrations.AlterModelOptions(
            name='venom',
            options={'verbose_name': 'Toxicologie', 'verbose_name_plural': 'Toxixcologies'},
        ),
    ]
