# Generated by Django 2.0.2 on 2018-02-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reptiles', '0005_auto_20180220_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lizard',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='lizard',
            name='life',
        ),
        migrations.RemoveField(
            model_name='lizard',
            name='repartition',
        ),
        migrations.RemoveField(
            model_name='lizard',
            name='reproduction',
        ),
        migrations.DeleteModel(
            name='Lizard',
        ),
    ]
