# Generated by Django 2.0.2 on 2018-02-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reptiles', '0006_auto_20180220_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snake',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='snake',
            name='family',
        ),
        migrations.RemoveField(
            model_name='snake',
            name='life',
        ),
        migrations.RemoveField(
            model_name='snake',
            name='repartition',
        ),
        migrations.RemoveField(
            model_name='snake',
            name='reproduction',
        ),
        migrations.RemoveField(
            model_name='snake',
            name='venom',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='Snake',
        ),
        migrations.DeleteModel(
            name='Venom',
        ),
    ]
