# Generated by Django 2.0.2 on 2018-02-24 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snake', '0008_auto_20180224_2155'),
        ('lizard', '0004_auto_20180224_2155'),
        ('reptiles', '0007_auto_20180220_2054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Life',
        ),
        migrations.DeleteModel(
            name='Reproduction',
        ),
    ]
